services:
  - type: web
    name: live-polling-system
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        value: mongodb string
      - key: PORT
        value: 3001
